unit TestuFrameVote;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Variants, uJsonObjectHelper, uApiDemocraticLunchConstants,
  Winapi.Windows, Vcl.Dialogs, uObjectBaseApi, Vcl.Forms, Vcl.Controls, uFrameVote,
  uVoting, System.Classes, System.SysUtils, Winapi.Messages, Data.DBXJSON, Vcl.Graphics,
  Vcl.StdCtrls, uApiComboboxHelper, uApiConsumption;

type
  // Test methods for class TframeVote

  TestTframeVote = class(TTestCase)
  strict private
    FframeVote: TframeVote;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestcbbRestaurantsClick;
    procedure TestLoadVoting;
    procedure TestVote;
  end;

implementation

procedure TestTframeVote.SetUp;
begin
  FframeVote := TframeVote.Create(nil);
end;

procedure TestTframeVote.TearDown;
begin
  FframeVote.Free;
  FframeVote := nil;
end;

procedure TestTframeVote.TestcbbRestaurantsClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FframeVote.cbbRestaurantsClick(Sender);
  // TODO: Validate method results
end;

procedure TestTframeVote.TestLoadVoting;
begin
  FframeVote.LoadVoting;
  // TODO: Validate method results
end;

procedure TestTframeVote.TestVote;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FframeVote.Vote;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTframeVote.Suite);
end.

